# name: trestapkmamabot
# description: "A new Flutter project."

# publish_to: 'none'


# version: 1.0.0+1

# environment:
#   sdk: '>=3.2.3 <4.0.0'


# dependencies:
#   flutter:
#     sdk: flutter
#   dialog_flowtter: ^0.3.1 
#   cupertino_icons: ^1.0.2
#   firebase_auth: ^4.20.0
#   firebase_core: ^2.32.0
#   firebase_storage: ^11.7.7
#   flutter_svg: ^2.0.9
#   # image_cropper: ^4.0.1
#   iconsax: ^0.0.8
#   # fluttertoast: ^8.2.5
#   intl: ^0.17.0
#   animations: ^2.0.1
#   font_awesome_flutter: ^9.1.0
#   get: ^4.1.4
#   lottie: ^1.0.1
#   readmore: ^2.1.0
#   cloud_firestore: ^4.17.5
#   shared_preferences: ^2.2.3
#   image_picker: ^1.1.2
#   firebase_app_check: ^0.2.2+7
#   skeleton_text: ^3.0.1
#   shimmer: ^3.0.0
#   flutter_launcher_icons: ^0.13.1

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon/ic_launcher_mamabot2/1024.png"
#   min_sdk_android: 21 
#   flutter_lints: ^2.0.0

# flutter:


#   uses-material-design: true


#   assets:
#     - assets/dialog_flow_auth.json
#     - assets/images/
#     - assets/icon/
  
#   fonts:
    
#     - family: Poppins
#       fonts:
#         - asset: assets/font/Poppins/Poppins-Black.ttf
#         - asset: assets/font/Poppins/Poppins-Bold.ttf
#         - asset: assets/font/Poppins/Poppins-Light.ttf
#         - asset: assets/font/Poppins/Poppins-Medium.ttf
#         - asset: assets/font/Poppins/Poppins-Regular.ttf
#         - asset: assets/font/Poppins/Poppins-Semibold.ttf
#         - asset: assets/font/Poppins/Poppins-Thin.ttf

#     - family: Inter
#       fonts:
#         - asset: assets/font/Inter/static/Inter-Thin.ttf
#         - asset: assets/font/Inter/static/Inter-ExtraLight.ttf
#         - asset: assets/font/Inter/static/Inter-Light.ttf
#         - asset: assets/font/Inter/static/Inter-Regular.ttf
#         - asset: assets/font/Inter/static/Inter-Medium.ttf
#         - asset: assets/font/Inter/static/Inter-SemiBold.ttf
#         - asset: assets/font/Inter/static/Inter-Bold.ttf
#         - asset: assets/font/Inter/static/Inter-ExtraBold.ttf
#         - asset: assets/font/Inter/static/Inter-Black.ttf
  


name: trestapkmamabot
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  dialog_flowtter: ^0.3.1 
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_storage: ^11.7.7
  flutter_svg: ^2.0.9
  # image_cropper: ^4.0.1
  iconsax: ^0.0.8
  # fluttertoast: ^8.2.5
  intl: ^0.17.0
  animations: ^2.0.1
  font_awesome_flutter: ^9.1.0
  get: ^4.1.4
  lottie: ^1.0.1
  readmore: ^2.1.0
  cloud_firestore: ^4.17.5
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  firebase_app_check: ^0.2.2+7
  skeleton_text: ^3.0.1
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ic_launcher_mamabot2/1024.png"
  min_sdk_android: 21 
  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/default_profile.png
    - assets/dialog_flow_auth.json
    - assets/images/
    - assets/icon/
  
  fonts:
    
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins/Poppins-Black.ttf
        - asset: assets/font/Poppins/Poppins-Bold.ttf
        - asset: assets/font/Poppins/Poppins-Light.ttf
        - asset: assets/font/Poppins/Poppins-Medium.ttf
        - asset: assets/font/Poppins/Poppins-Regular.ttf
        - asset: assets/font/Poppins/Poppins-Semibold.ttf
        - asset: assets/font/Poppins/Poppins-Thin.ttf

    - family: Inter
      fonts:
        - asset: assets/font/Inter/static/Inter-Thin.ttf
        - asset: assets/font/Inter/static/Inter-ExtraLight.ttf
        - asset: assets/font/Inter/static/Inter-Light.ttf
        - asset: assets/font/Inter/static/Inter-Regular.ttf
        - asset: assets/font/Inter/static/Inter-Medium.ttf
        - asset: assets/font/Inter/static/Inter-SemiBold.ttf
        - asset: assets/font/Inter/static/Inter-Bold.ttf
        - asset: assets/font/Inter/static/Inter-ExtraBold.ttf
        - asset: assets/font/Inter/static/Inter-Black.ttf
  
