// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDskGqDyzTg2XLzg-JV8DhyXaQ9H2XkSk',
    appId: '1:807331863603:web:ba4f848709753c0d0b1746',
    messagingSenderId: '807331863603',
    projectId: 'mamabot-4eba5',
    authDomain: 'mamabot-4eba5.firebaseapp.com',
    storageBucket: 'mamabot-4eba5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhMev_PzygQtf71x4wk5RtHpsoHRKKDpI',
    appId: '1:807331863603:android:24864de9fb9a5e040b1746',
    messagingSenderId: '807331863603',
    projectId: 'mamabot-4eba5',
    storageBucket: 'mamabot-4eba5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-quFb7kw9226Xu14LdLh_f1it7zbU1Go',
    appId: '1:807331863603:ios:24ba444e3d076a250b1746',
    messagingSenderId: '807331863603',
    projectId: 'mamabot-4eba5',
    storageBucket: 'mamabot-4eba5.appspot.com',
    iosClientId:
        '807331863603-g2k9ljs1jgdgr66p1iivcqr4e757v2kr.apps.googleusercontent.com',
    iosBundleId: 'com.example.trestapkmamabot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-quFb7kw9226Xu14LdLh_f1it7zbU1Go',
    appId: '1:807331863603:ios:24ba444e3d076a250b1746',
    messagingSenderId: '807331863603',
    projectId: 'mamabot-4eba5',
    storageBucket: 'mamabot-4eba5.appspot.com',
    iosClientId:
        '807331863603-g2k9ljs1jgdgr66p1iivcqr4e757v2kr.apps.googleusercontent.com',
    iosBundleId: 'com.example.trestapkmamabot',
  );
}
